name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}

    - name: Copy files via SCP
      run: |
        scp -o StrictHostKeyChecking=no -r ./* user@your_server_ip:/path/to/deployment/directory

    - name: Execute remote command
      run: |
        ssh -o StrictHostKeyChecking=no user@your_server_ip "cd /path/to/deployment/directory && ./deploy_script.sh"
